version: "3.9"

services:
  app:
    build: .
    container_name: backend-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    restart: always
